### Задание 1

In [42]:
import numpy as np

In [43]:
a = ([[1, 6],
      [2, 8],
     [3, 11],
     [3, 10],
     [1, 7]])

In [44]:
mean_a = np.mean(a, axis = 0)

In [45]:
mean_a

array([2. , 8.4])

###  Задание 2

In [46]:
a_centered = a - mean_a

In [47]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [48]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
print(a_centered_sp)

8.0


In [49]:
print(a_centered_sp / (a_centered.shape[0] - 1))

2.0


In [51]:
np.cov(a.T)[0, 1]

AttributeError: 'list' object has no attribute 'T'

In [36]:
a_centered.shape[0]

5

In [40]:
a_centered.T[0]

array([-1.,  0.,  1.,  1., -1.])